org.gradle.jvmargs=-Xmx1024M -XX:MaxMetaspaceSize=384M -XX:ReservedCodeCacheSize=128m
org.gradle.daemon=false
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
kotlin.compiler.execution.strategy=in-process

org.gradle.java.home=/home/z/jdk21
org.gradle.workers.max=1
org.gradle.parallel=false
kotlin.compiler.execution.strategy=in-process
